### ISSUE TITLE
Error: Error setting TTL index on collection : sessions

### ISSUE THREAD

**Issue by chidambaramnarayan** [EastpointSoftware/traider.io#28]
Does anyone know how to fix the below error
/Users/chidambaramiyer/Downloads/traider.io/node_modules/mongodb/lib/mongodb/connection/base.js:242
        throw message;      
              ^
Error: Error setting TTL index on collection : sessions
    at /Users/chidambaramiyer/Downloads/traider.io/node_modules/connect-mongo/lib/connect-mongo.js:161:23
    at /Users/chidambaramiyer/Downloads/traider.io/node_modules/mongodb/lib/mongodb/db.js:1430:36
    at __executeInsertCommand (/Users/chidambaramiyer/Downloads/traider.io/node_modules/mongodb/lib/mongodb/db.js:1829:12)
    at Db._executeInsertCommand (/Users/chidambaramiyer/Downloads/traider.io/node_modules/mongodb/lib/mongodb/db.js:1930:5)
    at /Users/chidambaramiyer/Downloads/traider.io/node_modules/mongodb/lib/mongodb/db.js:1427:14
    at /Users/chidambaramiyer/Downloads/traider.io/node_modules/mongodb/lib/mongodb/db.js:1560:7
    at /Users/chidambaramiyer/Downloads/traider.io/node_modules/mongodb/lib/mongodb/cursor.js:162:16
    at commandHandler (/Users/chidambaramiyer/Downloads/traider.io/node_modules/mongodb/
b/lib/mongodb/db.js:1930:5)
    at /Users/chidambaramiyer/Downloads/traider.io/node_modules/mongodb/lib/mongodb/db.js:1427:14
    at /Users/chidambaramiyer/Downloads/traider.io/node_modules/mongodb/lib/mongodb/db.js:1560:7
    at /Users/chidambaramiyer/Downloads/traider.io/node_modules/mongodb/lib/mongodb/cursor.js:162:16
    at commandHandler (/Users/chidambaramiyer/Downloads/traider.io/node_modules/mongodb/lib/mongodb/cursor.js:706:16)
    at /Users/chidambaramiyer/Downloads/traider.io/node_modules/mongodb/lib/mongodb/db.js:1806:9
    at Server.Base._callHandler (/Users/chidambaramiyer/Downloads/traider.io/node_modules/mongodb/lib/mongodb/connection/base.js:442:41)

**Comment by zorobabel** [comment]
This is the root of the problem:

{ [MongoError: driver is incompatible with this server version] name: 'MongoError' }

**Comment by Us-marshal** [comment]
Did you resolve this error?  I am having the same issue and have tried several different Mongodb versions with no success.

**Comment by chidambaramnarayan** [comment]
No

**Comment by Us-marshal** [comment]
As a total hack just to get it running, I commented out the line throwing the exception on line 161 of connect-mongo.js

if (err) {
   **_ //throw new Error('Error setting TTL index on collection : ' + self.db_collection_name);_**
 }

Overall the app is very incomplete and seems to have been abandoned.  Not really worth the effort imho.

Cheers -

**Comment by chidambaramnarayan** [comment]
Same here I tried and no support provided hence did not pursue further

**Comment by Pawan-Bishnoi** [comment]
This is quite old but anyways i felt like sharing my findings.
This is due to mongo db version mismatch.

This solved it for me:
 npm install mongodb@1.4.x

**Comment by rohitbajaniya** [comment]
@Pawan-Bishnoi 

After install mongodb@1.4.x
gives the error "Cannot find module '../build/Release/bson'"
