### ISSUE TITLE
Error setting TTL index on collection : sessions

### ISSUE THREAD

**Issue by madhawik** [EastpointSoftware/traider.io#35]
I have nodejs installed locally. Aslo mongodb installed & running locally. I cloned traider application on my server. Then I run `npm insta`ll command. And then started `node traider.js`. Then  opened http://localhost:5000/api/products/seed to create some dummy product data. After this getting below error. 

`c:\mkwork\attic\traider\node_modules\connect-mongo\node_modules\mongodb\lib\mongodb\connection\base.js:242
        throw message;
        ^

Error: Error setting TTL index on collection : sessions
    at c:\mkwork\attic\traider\node_modules\connect-mongo\lib\connect-mongo.js:161:23
    at c:\mkwork\attic\traider\node_modules\connect-mongo\node_modules\mongodb\lib\mongodb\db.js:1430:36
    at __executeInsertCommand (c:\mkwork\attic\traider\node_modules\connect-mongo\node_modules\mongodb\lib\mon
godb\db.js:1829:12)
    at Db._executeInsertCommand (c:\mkwork\attic\traider\node_modules\connect-mongo\node_modules\mongodb\lib\m
ongodb\db.js:1930:5)
    at c:\mkwork\attic\traider\node_modules\connect-mongo\node_modules\mongodb\lib\mongodb\db.js:1427:14
    at c:\mkwork\attic\traider\node_modules\connect-mongo\node_modules\mongodb\lib\mongodb\db.js:1560:7
    at c:\mkwork\attic\traider\node_modules\connect-mongo\node_modules\mongodb\lib\mongodb\cursor.js:162:16
    at commandHandler (c:\mkwork\attic\traider\node_modules\connect-mongo\node_modules\mongodb\lib\mongodb\cur
sor.js:706:16)
    at c:\mkwork\attic\traider\node_modules\connect-mongo\node_modules\mongodb\lib\mongodb\db.js:1806:9
    at Server.Base._callHandler (c:\mkwork\attic\traider\node_modules\connect-mongo\node_modules\mongodb\lib\m
ongodb\connection\base.js:442:41)
`

Thanks,
Madhawi

**Comment by MikeLucia** [comment]
I'm currently having the same issue, did you happen to resolve this since posting?

**Comment by ingenmaffen** [comment]
I managed to fix the issue:
https://github.com/EastpointSoftware/traider.io/pull/39
