### ISSUE TITLE
Error: Cannot determine state of server - localhost:5000/api/products/seed

### ISSUE THREAD

**Issue by KingKush** [EastpointSoftware/traider.io#37]
I'm getting this error inside powershell...
Error: Error setting TTL index on collection : sessions
    at C:\xampp\htdocs\NodeComm\traider.io\node_modules\connect-mongo\lib\connec
t-mongo.js:161:23

And when I navigate to api/products/seed, I get this error. Someone please help me here.
Also, when I load the page initially I get an alert box with an error.
Error: Cannot determine state of server
   at canCheckoutReader (C:\xampp\htdocs\NodeComm\traider.io\node_modules\mongodb\lib\mongodb\connection\server.js:767:12)
   at Server.checkoutReader (C:\xampp\htdocs\NodeComm\traider.io\node_modules\mongodb\lib\mongodb\connection\server.js:779:16)
   at Cursor.nextObject (C:\xampp\htdocs\NodeComm\traider.io\node_modules\mongodb\lib\mongodb\cursor.js:720:48)
   at Cursor.nextObject (C:\xampp\htdocs\NodeComm\traider.io\node_modules\mongodb\lib\mongodb\scope.js:22:20)
   at Collection.findOne (C:\xampp\htdocs\NodeComm\traider.io\node_modules\mongodb\lib\mongodb\collection\query.js:145:10)
   at C:\xampp\htdocs\NodeComm\traider.io\node_modules\connect-mongo\lib\connect-mongo.js:214:18
   at MongoStore._get_collection (C:\xampp\htdocs\NodeComm\traider.io\node_modules\connect-mongo\lib\connect-mongo.js:148:21)
   at MongoStore.get (C:\xampp\htdocs\NodeComm\traider.io\node_modules\connect-mongo\lib\connect-mongo.js:213:10)
   at Object.session [as handle] (C:\xampp\htdocs\NodeComm\traider.io\node_modules\express-session\index.js:460:11)
   at next (C:\xampp\htdocs\NodeComm\traider.io\node_modules\connect\lib\proto.js:174:15)

**Comment by mrkhanakia** [comment]
Same error anybody has the solution ?
