### ISSUE TITLE
MongoDB version supported

### ISSUE THREAD

**Issue by thinkMX** [EastpointSoftware/traider.io#38]
I'd like to know which is the latest version of mongoDB supported fot this project.
I'm trying with lastest version (3.4.7) Windows x64 and when I run the command

node .\traider.js

This error araises:
Failed to load c++ bson extension, using pure JS version
express-session deprecated undefined resave option; provide resave option traider.js:21:16
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option traider.js:21:16
Listening on 5000
C:\Users\XXX\Documents\ECOMERCE\traider.io\node_modules\mongodb\lib\mongodb\connection\base.js:242
        throw message;
        ^

Error: Error setting TTL index on collection : sessions
    at C:\Users\XXX\Documents\ECOMERCE\traider.io\node_modules\connect-mongo\lib\connect-mongo.js:161:23
    at C:\Users\XXX\Documents\ECOMERCE\traider.io\node_modules\mongodb\lib\mongodb\db.js:1430:36
    at __executeInsertCommand (C:\Users\XXX\Documents\ECOMERCE\traider.io\node_modules\mongodb\lib\mongodb\db.js:1829:12)
    at Db._executeInsertCommand (C:\Users\XXX\Documents\ECOMERCE\traider.io\node_modules\mongodb\lib\mongodb\db.js:1930:5)
    at C:\Users\XXX\Documents\ECOMERCE\traider.io\node_modules\mongodb\lib\mongodb\db.js:1427:14
    at C:\Users\XXX\Documents\ECOMERCE\traider.io\node_modules\mongodb\lib\mongodb\db.js:1560:7
    at C:\Users\XXX\Documents\ECOMERCE\traider.io\node_modules\mongodb\lib\mongodb\cursor.js:162:16
    at commandHandler (C:\Users\XXX\Documents\ECOMERCE\traider.io\node_modules\mongodb\lib\mongodb\cursor.js:706:16)
    at C:\Users\XXX\Documents\ECOMERCE\traider.io\node_modules\mongodb\lib\mongodb\db.js:1806:9
    at Server.Base._callHandler (C:\Users\XXX\Documents\ECOMERCE\traider.io\node_modules\mongodb\lib\mongodb\connection\base.js:442:41)

Please help!
Do I need a legacy version of mongoDB fot this project to work?

**Comment by thinkMX** [comment]
![image](https://user-images.githubusercontent.com/2821668/29243348-8fa0e86c-7f62-11e7-820f-3abfac7d281d.png)

As you can see, I have already installed mongoDB locally and I have acces to it with no security enabled, listening on default port

**Comment by Saravanan101092** [comment]
Having same issue.

**Comment by MichaelLogic** [comment]
@thinkMX and @Saravanan101092  have you solved this issue? 
I have resolved all warnings and incompatibilities leading up to the product seed script.

**Comment by Saravanan101092** [comment]
@MichaelLogic: Nope. I have given up on this Traider. Looks like the MongoDB version they are using is old.

**Comment by Insidebox** [comment]
Error: Cannot determine state of server
   at canCheckoutReader (/Users/insidebox/Documents/GitHub/la-room-studio-traderio/node_modules/mongodb/lib/mongodb/connection/server.js:767:12)
   at Server.checkoutReader (/Users/insidebox/Documents/GitHub/la-room-studio-traderio/node_modules/mongodb/lib/mongodb/connection/server.js:779:16)
   at Cursor.nextObject (/Users/insidebox/Documents/GitHub/la-room-studio-traderio/node_modules/mongodb/lib/mongodb/cursor.js:720:48)
   at Cursor.nextObject (/Users/insidebox/Documents/GitHub/la-room-studio-traderio/node_modules/mongodb/lib/mongodb/scope.js:22:20)
   at Collection.findOne (/Users/insidebox/Documents/GitHub/la-room-studio-traderio/node_modules/mongodb/lib/mongodb/collection/query.js:145:10)
   at /Users/insidebox/Documents/GitHub/la-room-studio-traderio/node_modules/connect-mongo/lib/connect-mongo.js:214:18
   at MongoStore._get_collection (/Users/insidebox/Documents/GitHub/la-room-studio-traderio/node_modules/connect-mongo/lib/connect-mongo.js:148:21)
   at MongoStore.get (/Users/insidebox/Documents/GitHub/la-room-studio-traderio/node_modules/connect-mongo/lib/connect-mongo.js:213:10)
   at Object.session [as handle] (/Users/insidebox/Documents/GitHub/la-room-studio-traderio/node_modules/express-session/index.js:460:11)
   at next (/Users/insidebox/Documents/GitHub/la-room-studio-traderio/node_modules/connect/lib/proto.js:174:15)

**Comment by MichaelLogic** [comment]
Yes.  I can relate to your issues.
Take a look into my updated package and see if it provides any insight.
[Error-free Traider package](https://github.com/MichaelLogic/traider.io)
